--- 
groups: 
  portada: 
  - &id002 
    group: portada
    name: portada-ancha.jpg
    height: 707
    path: portada/portada-ancha.jpg
    width: 1488
  - &id009 
    group: portada
    name: portada1200.jpg
    height: 1200
    path: portada/portada1200.jpg
    width: 2639
  blog: 
  - &id008 
    group: blog
    name: fondo-blog1.jpg
    height: 524
    path: blog/fondo-blog1.jpg
    width: 760
  - &id011 
    group: blog
    name: fondo-blog.jpg
    height: 655
    path: blog/fondo-blog.jpg
    width: 950
  fondos: 
  - &id004 
    group: fondos
    name: neuronas1-1200.jpg
    height: 1200
    path: fondos/neuronas1-1200.jpg
    width: 1902
  - &id001 
    group: fondos
    name: fondo-dinero.jpg
    height: 1090
    path: fondos/fondo-dinero.jpg
    width: 2263
  dinero: 
  - &id006 
    group: dinero
    name: aa-comprando.jpg
    height: 872
    path: dinero/aa-comprando.jpg
    width: 613
  - &id003 
    group: dinero
    name: a-trabajador-ideal.jpg
    height: 568
    path: dinero/a-trabajador-ideal.jpg
    width: 567
  - &id010 
    group: dinero
    name: apocalipsis-grises.jpg
    height: 567
    path: dinero/apocalipsis-grises.jpg
    width: 803
  elotromundo: 
  - &id012 
    group: elotromundo
    name: 1484-disney-wall.jpg
    height: 703
    path: elotromundo/1484-disney-wall.jpg
    width: 940
  - &id007 
    group: elotromundo
    name: "1538-tonter\xC3\xADa-perfecta.jpg"
    height: 703
    path: "elotromundo/1538-tonter\xC3\xADa-perfecta.jpg"
    width: 949
  - &id005 
    group: elotromundo
    name: 1437-peleas-en-parlamentos.jpg
    height: 703
    path: elotromundo/1437-peleas-en-parlamentos.jpg
    width: 851
images: 
  fondo-dinero.jpg: *id001
  portada-ancha.jpg: *id002
  a-trabajador-ideal.jpg: *id003
  neuronas1-1200.jpg: *id004
  1437-peleas-en-parlamentos.jpg: *id005
  aa-comprando.jpg: *id006
  "1538-tonter\xC3\xADa-perfecta.jpg": *id007
  fondo-blog1.jpg: *id008
  portada1200.jpg: *id009
  apocalipsis-grises.jpg: *id010
  fondo-blog.jpg: *id011
  1484-disney-wall.jpg: *id012
